parameters:
- name: environment
- name: webAppName
- name: subscription
- name: artifactName
  default: drop

jobs:
- deployment: deploy_app_service
  displayName: deploy to ${{ parameters.environment }} environment
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: ${{ parameters.subscription }}
            appType: 'webApp'
            WebAppName: ${{ parameters.webAppName }}
            packageForLinux: '$(Pipeline.Workspace)/${{ parameters.artifactName}}/**/*.zip'
            enableXmlVariableSubstitution: true