trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - consumer

resources:
  containers:
    - container: pact_cli
      image: pactfoundation/pact-cli:latest

pool:
    vmImage: ubuntu-latest

stages:
# - stage: build
#   jobs:
#   - job: build
#     steps:
#       - task: DotNetCoreCLI@2
#         displayName: build
#         inputs:
#           command: build
#           arguments: 'consumer/consumer/consumer.csproj --configuration Release'
#       - task: DotNetCoreCLI@2
#         displayName: test
#         inputs:
#           command: test
#           arguments: 'consumer/Consumer.Test.NUnit/Consumer.Test.NUnit.csproj --configuration Release'
#       - task: CopyFiles@2
#         displayName: stage pacts
#         inputs:
#           sourceFolder: 'consumer/Consumer.Test.NUnit'
#           contents: 'pacts/*.json'
#           targetFolder: '$(Build.ArtifactStagingDirectory)'
#       - task: PublishBuildArtifacts@1
#         displayName: publish artifacts
#         inputs:
#           pathToPublish: '$(Build.ArtifactStagingDirectory)'
#           artifactName: drop
      # - task: DotNetCoreCLI@2
      #   displayName: publish
      #   inputs:
      #     command: publish
      #     projects: consumer/consumer/consumer.csproj
      #     arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

- stage: publish

  variables:
  - name: git.commit.short.sha
    value: not-set
  - name: pact.broker.base.url
    value: not-set
  - name: pact.broker.api.token
    value: not-set

  jobs:
  - job: pact_publish
    displayName: pact publish
    services:
      pact_cli: pact_cli
    steps:
      - script: |
          sourceVersion=$(Build.SourceVersion)
          echo sourceVersion: $sourceVersion

          shortSha=${sourceVersion:0:7}
          echo shortSha: $shortSha

          echo "##vso[task.setvariable variable=gitCommitShortSha]$shortSha"
        displayName: set publish variables
      - script: |
          echo GIT_COMMIT_SHORT_SHA: $GIT_COMMIT_SHORT_SHA
          echo Build.SourceBranch: $(Build.SourceBranch)
          echo PACT_BROKER_BASE_URL: $PACT_BROKER_BASE_URL

          echo GIT_COMMIT_SHORT_SHA: $(git.commit.short.sha)
          echo PACT_BROKER_BASE_URL: $(pact.broker.base.url)
        displayName: show variables
      # - task: Docker@2
      #   displayName: will see
      #   inputs:
      #     command: login
      # - script: |
      #     docker run --rm pactfoundation/pact-cli:latest pact-broker publish pacts \
      #     --consumer-app-version=$GIT_COMMIT_SHORT_SHA \
      #     --tag=$(Build.SourceBranch) \
      #     --broker-base-url=$PACT_BROKER_BASE_URL \
      #     --broker-token=$PACT_BROKER_API_TOKEN
      #   displayName: docker run
      - script: |
          docker run --rm pactfoundation/pact-cli:latest help
        displayName: docker run
      # - script: |
      #     pact-broker publish pacts \
      #       --consumer-app-version=$GIT_COMMIT_SHORT_SHA \
      #       --tag=$(Build.SourceBranch) \
      #       --broker-base-url=$PACT_BROKER_BASE_URL \
      #       --broker-token=$PACT_BROKER_API_TOKEN
      #   displayName: pact-broker publish
        # target:
        #   container: pact_cli