trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Consumer

pool:
    vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: build
    continueOnError: 'false'
    steps:
      - task: DotNetCoreCLI@2
        displayName: build
        inputs:
          command: build
          arguments: '--configuration Release'