trigger:
  branches:
    include:
    - main
  paths:
    include:
    - consumer

pool:
    vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: build
    continueOnError: 'false'
    steps:
      - task: DotNetCoreCLI@2
        displayName: build
        inputs:
          command: build
          arguments: 'consumer/consumer/consumer.csproj --configuration Release'
      - task: DotNetCoreCLI@2
        displayName: test
        inputs:
          command: test
          arguments: 'consumer/Consumer.Test.NUnit/Consumer.Test.NUnit.csproj --configuration Release'