trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra

stages :
  - stage: validate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            displayName: 'install'
            inputs:
              terraformVersion: '0.14.7'
          - task: TerraformTaskV1@0
            displayName: 'init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'azure-tf-rg'
              backendAzureRmResourceGroupName: 'tf-rg'
              backendAzureRmStorageAccountName: 'svasqueztfsa01'
              backendAzureRmContainerName: 'tf-state-devops'
              backendAzureRmKey: 'terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/'
          - task: TerraformTaskV1@0
            displayName: 'validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'