trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - infra

stages :
  - stage: validate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            displayName: 'install'
            inputs:
              terraformVersion: '0.14.7'
          - task: TerraformTaskV1@0
            displayName: 'init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'azure-tf-rg'
              backendAzureRmResourceGroupName: 'tf-rg'
              backendAzureRmStorageAccountName: 'svasqueztfsa01'
              backendAzureRmContainerName: 'tf-state-devops'
              backendAzureRmKey: 'terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/'
          - task: TerraformTaskV1@0
            displayName: 'validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: deploy
    jobs:
      - deployment: deploy_terraform
        continueOnError: false
        environment: 'tooling'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformInstaller@0
                  displayName: 'install'
                  inputs:
                    terraformVersion: '0.14.7'
                - task: TerraformTaskV1@0
                  displayName: 'init'
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    backendServiceArm: 'azure-tf-rg'
                    backendAzureRmResourceGroupName: 'tf-rg'
                    backendAzureRmStorageAccountName: 'svasqueztfsa01'
                    backendAzureRmContainerName: 'tf-state-devops'
                    backendAzureRmKey: 'terraform.tfstate'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/'
                - task: TerraformTaskV1@0
                  displayName: 'plan'
                  inputs:
                    provider: 'azurerm'
                    command: 'plan'
                    environmentServiceNameAzureRM: 'azure-tf-rg'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/'
                - task: TerraformTaskV1@0
                  displayName: 'apply'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    environmentServiceNameAzureRM: 'azure-tf-rg'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/'