trigger: none

resources:
  webhooks:
    - webhook: pact_content_changed
      connection: vasquez_house_pactflow
      filters:
        - path: eventName
          value: contract_content_changed

pool:
  vmImage: ubuntu-latest
    
variables:
  - group: pactflow-variables

stages:
- stage: dev
  displayName: dev environment
  jobs:
  - job: test
    variables:
      GIT_COMMIT_SHORT_SHA: value-set-below
    steps:
      - script: |
          sourceVersion=$(Build.SourceVersion)
          echo sourceVersion: $sourceVersion

          shortSha=${sourceVersion:0:7}
          echo shortSha: $shortSha

          echo "##vso[task.setvariable variable=GIT_COMMIT_SHORT_SHA]$shortSha"
        displayName: get commit short sha
      - script: |
          dotnet test ProviderApi/ProviderApi.Test/ProviderApi.Test.csproj --configuration Release
        displayName: dotnet test
        env:
          CI: true
          PACT_BROKER_BASE_URL: $(pact.broker.base.url)
          PACT_BROKER_API_TOKEN: $(pact.broker.api.token)
          PACT_CONSUMER_NAME: ${{parameters.pact_content_changed.consumerName}}
          PACT_CONSUMER_TAG: ${{parameters.pact_content_changed.consumerTag}}
          PACT_PROVIDER_TAG: $(Build.SourceBranch)
          GIT_COMMIT_SHORT_SHA: $(GIT_COMMIT_SHORT_SHA)
          PROVIDER_FOO_API_BASE_URI: http://localhost:9333