trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - provider

resources:
  containers:
    - container: pact_cli
      image: pactfoundation/pact-cli:latest

pool:
    vmImage: ubuntu-latest
    
variables:
- group: pactflow-variables

stages:
- stage: dev
  displayName: dev environment

  jobs:
  - job: test
    steps:
      - task: DotNetCoreCLI@2
        displayName: dotnet test
        inputs:
          command: test
          arguments: 'provider/Provider.Test/Provider.Test.csproj --configuration Release'
        
  - job: check_pacts
    displayName: check pacts
    dependsOn: test
    services:
      pact_cli: pact_cli
    variables:
      GIT_COMMIT_SHORT_SHA: value-set-below
    steps:
      - script: |
          sourceVersion=$(Build.SourceVersion)
          echo sourceVersion: $sourceVersion

          shortSha=${sourceVersion:0:7}
          echo shortSha: $shortSha

          echo "##vso[task.setvariable variable=GIT_COMMIT_SHORT_SHA]$shortSha"
        displayName: get commit short sha
      - script: |
          docker run --rm \
            pactfoundation/pact-cli:latest \
            broker can-i-deploy \
            --pacticipant "Something API" \
            --version $GIT_COMMIT_SHORT_SHA \
            --to dev \
            --broker-base-url=$PACT_BROKER_BASE_URL \
            --broker-token=$PACT_BROKER_API_TOKEN \
            --verbose
        displayName: pact-broker can-i-deploy
        env:
          PACT_BROKER_BASE_URL: $(pact.broker.base.url)
          PACT_BROKER_API_TOKEN: $(pact.broker.api.token)