trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - provider

resources:
  containers:
    - container: pact_cli
      image: pactfoundation/pact-cli:latest

pool:
    vmImage: ubuntu-latest
    
variables:
- group: pactflow-variables

stages:
- stage: dev
  displayName: dev environment

  jobs:
  - job: test
    variables:
      GIT_COMMIT_SHORT_SHA: value-set-below
    steps:
      - script: |
          sourceVersion=$(Build.SourceVersion)
          echo sourceVersion: $sourceVersion

          shortSha=${sourceVersion:0:7}
          echo shortSha: $shortSha

          echo "##vso[task.setvariable variable=GIT_COMMIT_SHORT_SHA]$shortSha"
        displayName: get commit short sha
      - script: |
          dotnet test provider/Provider.Test/Provider.Test.csproj --configuration Release
        displayName: dotnet test
        env:
          CI: true
          PACT_BROKER_BASE_URL: $(pact.broker.base.url)
          PACT_BROKER_API_TOKEN: $(pact.broker.api.token)
          PACT_PROVIDER_TAG: $(Build.SourceBranch)
          GIT_COMMIT_SHORT_SHA: $(GIT_COMMIT_SHORT_SHA)
          PROVIDER_FOO_API_BASE_URI: http://localhost:9333 # todo: hardcode this value in the test
        
  - job: check_pacts
    displayName: check pacts
    dependsOn: test
    services:
      pact_cli: pact_cli
    variables:
      GIT_COMMIT_SHORT_SHA: value-set-below
    steps:
      - script: |
          sourceVersion=$(Build.SourceVersion)
          echo sourceVersion: $sourceVersion

          shortSha=${sourceVersion:0:7}
          echo shortSha: $shortSha

          echo "##vso[task.setvariable variable=GIT_COMMIT_SHORT_SHA]$shortSha"
        displayName: get commit short sha
      - script: |
          docker run --rm \
            pactfoundation/pact-cli:latest \
            broker can-i-deploy \
            --pacticipant "Something API" \
            --version $GIT_COMMIT_SHORT_SHA \
            --to dev \
            --broker-base-url=$PACT_BROKER_BASE_URL \
            --broker-token=$PACT_BROKER_API_TOKEN \
            --verbose
        displayName: pact-broker can-i-deploy
        env:
          PACT_BROKER_BASE_URL: $(pact.broker.base.url)
          PACT_BROKER_API_TOKEN: $(pact.broker.api.token)
          
  - job: deploy
    dependsOn: check_pacts
    services:
      pact_cli: pact_cli
    variables:
      GIT_COMMIT_SHORT_SHA: value-set-below
    steps:
      - script: |
          echo fake deployment step that assumes deployment was successful
        displayName: deploy (fake)
      - script: |
          sourceVersion=$(Build.SourceVersion)
          echo sourceVersion: $sourceVersion

          shortSha=${sourceVersion:0:7}
          echo shortSha: $shortSha

          echo "##vso[task.setvariable variable=GIT_COMMIT_SHORT_SHA]$shortSha"
        displayName: get commit short sha        
      - script: |
          docker run --rm \
            pactfoundation/pact-cli:latest \
            broker create-version-tag \
            --pacticipant "Something API" \
            --version $GIT_COMMIT_SHORT_SHA \
            --tag dev \
            --broker-base-url=$PACT_BROKER_BASE_URL \
            --broker-token=$PACT_BROKER_API_TOKEN \
            --verbose
        displayName: pact-broker create-version-tag
        env:
          PACT_BROKER_BASE_URL: $(pact.broker.base.url)
          PACT_BROKER_API_TOKEN: $(pact.broker.api.token)