trigger: none

resources:
  webhooks:
  - webhook: test-webhook-05
    connection: test-connection-05

pool:
    vmImage: ubuntu-latest

stages:
- stage: dev
  displayName: dev environment
  jobs:
  - job: test
    variables:
      GIT_COMMIT_SHORT_SHA: value-set-below
    steps:
      - script: |
          sourceVersion=$(Build.SourceVersion)
          echo sourceVersion: $sourceVersion

          shortSha=${sourceVersion:0:7}
          echo shortSha: $shortSha

          echo "##vso[task.setvariable variable=GIT_COMMIT_SHORT_SHA]$shortSha"
        displayName: get commit short sha
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            Write-Host ${{ parameters.consumerPactUri}}
        displayName: debug webhook payload
      - script: |
          dotnet test provider/Provider.Test/Provider.Test.csproj --configuration Release
        displayName: dotnet test
        env:
          PROVIDER_FOO_API_BASE_URI: http://localhost:9333
          CONSUMER_PACT_URI: $(consumerPactUri)
          PACT_BROKER_API_TOKEN: $(pact.broker.api.token)
          GIT_COMMIT_SHORT_SHA: $(GIT_COMMIT_SHORT_SHA)
          CI: true