parameters:
- name: test-webhook-05
  displayName: webhook payload
  type: object

trigger: none

resources:
  webhooks:
  - webhook: test-webhook-05
    connection: test-connection-05

pool:
    vmImage: ubuntu-latest

stages:
- stage: dev
  displayName: dev environment
  jobs:
  - job: test
    variables:
      GIT_COMMIT_SHORT_SHA: value-set-below
      CONSUMER_PACT_URI1: ${{parameters.test-webhook-05.consumerPactUri}}
    steps:
      - script: |
          sourceVersion=$(Build.SourceVersion)
          echo sourceVersion: $sourceVersion

          shortSha=${sourceVersion:0:7}
          echo shortSha: $shortSha

          echo "##vso[task.setvariable variable=GIT_COMMIT_SHORT_SHA]$shortSha"
        displayName: get commit short sha
      - script: |
          echo CONSUMER_PACT_URI1: $(CONSUMER_PACT_URI1)
        displayName: debug webhook payload
      - script: |
          dotnet test provider/Provider.Test/Provider.Test.csproj --configuration Release
        displayName: dotnet test
        env:
          PROVIDER_FOO_API_BASE_URI: http://localhost:9333
          CONSUMER_PACT_URI: $(parameters.test-webhook-05.consumerPactUri)
          PACT_BROKER_API_TOKEN: $(pact.broker.api.token)
          GIT_COMMIT_SHORT_SHA: $(GIT_COMMIT_SHORT_SHA)
          CI: true